# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Camilo Escobar-Velásquez
tagline:          'Ph.D. Student and Ultimate Frisbee Player'
description:      'Ph.D. Student and Ultimate Frisbee Player'
url:              https://caev03.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Camilo Escobar-Velásquez'
  url:            https://twitter.com/caev03
  email:          ca.escobar2434@uniandes.edu.co

# paginate:         0
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
scholar:
  style: apa
  source: ./_bibliography
  sort_by: year
  order: descending
  bibliography_template: bib
  
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-scholar
  - jekyll-octicons

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo: https://github.com/caev03
twitter: https://twitter.com/caev03
linkedin: https://www.linkedin.com/in/caev03/
instagram: https://www.instagram.com/caev03/
gscholar: https://scholar.google.com/citations?user=cOGjd9kAAAAJ&hl=es

defaults:
  - scope:
      path: "assets/imgs"
    values:
      image: true